language: ruby

before_install:
  - gem install bundler

bundler_args: --jobs=3 --retry=3

cache: bundler

rvm:
  - 1.8.7
  - 2.3.0

matrix:
  exclude:
    - rvm: 1.8.7
      env:
    - rvm: 2.3.0
      env: PUPPET_VERSION='~> 3.8.7' RAKE_VERSION='~> 10.1'

env:
  - PUPPET_VERSION='~> 3.8.7' RAKE_VERSION='~> 10.1'
  -
