language: ruby

before_install:
  - gem install bundler

bundler_args: --jobs=3 --retry=3

cache: bundler

rvm:
  - 1.9.3
  - 2.2.0

matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION=4.5
    - rvm: 2.2.0
      env: PUPPET_VERSION=3.8.7

env:
  - PUPPET_VERSION=3.8.7
  - PUPPET_VERSION=4.5
