language: ruby

before_install:
  - gem install bundler

bundler_args: --jobs=3 --retry=3

cache: bundler

rvm:
  - 1.8.7
  - 2.2

matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.5.2
    - rvm: 2.2
      jdk: PUPPET_VERSION=3.8.7

env:
  - PUPPET_VERSION=3.8.7
  - PUPPET_VERSION=4.5.2
